layout_spectrum: 0.3382928
typography_spectrum: 0.7545857
color:
  saturation: 0.642526
  lightness: 0.3422141
  brandStrength: 0.4054738
  rhythmicContrast: 0.2006776
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Funksjonell testing
