name: Funksjonelle tester
favicon: null
layout_spectrum: 0.50253
typography_spectrum: 0.83526
title: Funksjonelle Tester og Fundamental Trening
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#f19914'
    - '#000000'
    - '#686868'
    - '#adadad'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
