name: Funksjonelle tester
favicon: null
layout_spectrum: 0.50253
typography_spectrum: 0.83526
title: Funksjonelle Tester og Fundamental Trening
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75910333-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#323232'
    - '#5d860c'
    - '#b2b2b2'
    - '#626262'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
