name: Funksjonelle tester
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3798
title: Funksjonelle Tester og Fundamental Trening
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75910333-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#323232'
    - '#5d860c'
    - '#b2b2b2'
    - '#626262'
  brandStrength: 0.125
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
