typography_spectrum: 1
color:
  saturation: 0.125
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#33AACD'
    - '#848384'
    - '#061519'
    - '#195566'
    - '#4A494A'
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4085106
analytics:
  twitter: null
  google: UA-76297240-1
  facebook: null
name: 2FT.io
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Om 2FT.io
    id: 54cc60e2-effd-4066-a32f-8500427431ee
    type: content
  - name: Bedrift
    id: 470036d7-08be-4ab9-9675-da1539bacd53
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: SNØLYKKAN TERAPEUTISKA
purpose: []
